<template>
  <div class="export-demo">
    <n-data-table
      :columns="columns"
      :data="tableData"
      :summary="summary"
      bordered
      ref="tableRef"
    />
    <n-button 
      type="primary" 
      @click="handleExportPDF"
      style="margin-top: 20px;"
    >
      Export to PDF
    </n-button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { NDataTable, NButton } from 'naive-ui'
import { ExportPDFTable } from 'vue-doc-exporter'

// Sample table data
const tableData = ref([
  { id: 1, name: 'John Smith', age: 32, department: 'Sales', salary: 4500 },
  { id: 2, name: 'Sarah Johnson', age: 28, department: 'Marketing', salary: 3800 },
  { id: 3, name: 'Michael Brown', age: 41, department: 'IT', salary: 6200 },
  { id: 4, name: 'Emily Davis', age: 24, department: 'HR', salary: 3500 },
  { id: 5, name: 'Robert Wilson', age: 36, department: 'Sales', salary: 4800 },
  { id: 6, name: 'Jennifer Lee', age: 29, department: 'Marketing', salary: 4100 },
  { id: 7, name: 'David Miller', age: 45, department: 'IT', salary: 6700 },
  { id: 8, name: 'Lisa Taylor', age: 31, department: 'HR', salary: 3900 },
  { id: 9, name: 'James Anderson', age: 38, department: 'Sales', salary: 5200 },
  { id: 10, name: 'Mary Thomas', age: 27, department: 'Marketing', salary: 4300 }
])

// Table columns configuration
const columns = ref([
  { title: 'ID', key: 'id', width: 80 },
  { title: 'Full Name', key: 'name' },
  { title: 'Age', key: 'age', width: 100 },
  { title: 'Department', key: 'department' },
  { 
    title: 'Monthly Salary ($)', 
    key: 'salary',
    render: (row: any) => {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0
      }).format(row.salary)
    }
  }
])

// Summary function for the table
const summary = () => {
  const totalAge = tableData.value.reduce((sum, row) => sum + row.age, 0)
  const totalSalary = tableData.value.reduce((sum, row) => sum + row.salary, 0)
  
  return {
    name: {
      value: 'TOTAL',
      colSpan: 3
    },
    age: {
      value: totalAge,
      colSpan: 1
    },
    salary: {
      value: new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0
      }).format(totalSalary),
      colSpan: 1
    }
  }
}

// PDF Export function
const handleExportPDF = async () => {
  try {
    // Prepare summary data
    const summaryData = {
      name: 'TOTAL',
      age: summary().age.value.toString(),
      department: '',
      salary: tableData.value.reduce((sum, row) => sum + row.salary, 0).toLocaleString()
    }

    // Format the content for export
    const content = {
      data: tableData.value.map(item => ({
        ...item,
        salary: new Intl.NumberFormat('en-US', {
          style: 'currency',
          currency: 'USD',
          minimumFractionDigits: 0
        }).format(item.salary)
      })),
      columns: columns.value.map(col => col.title),
      headers: [
        { 
          type: 'boxed-header',
          content: [
            `Report Date: ${new Date().toLocaleDateString()}`,
            `Total Employees: ${tableData.value.length}`,
            `Generated by: HR Department`
          ] 
        }
      ],
      title: 'Employee Salary Report',
      logo: '/company-logo.png',
      logoText: 'ACME Corporation',
      summary: summaryData
    }

    // PDF export attributes
    const attributes = {
      font: 'Helvetica',
      fontSize: 10,
      color: '#333333',
      uppercaseTitle: true,
      themes: 'striped',
      logoHeight: 30,
      logoWidth: 80,
      language: 'en'
    }

    await ExportPDFTable(
      `employee-salaries-${new Date().toISOString().slice(0, 10)}`,
      content,
      attributes
    )
    
  } catch (error) {
    console.error('PDF Export Error:', error)
  }
}
</script>

<style scoped>
.export-demo {
  padding: 20px;
  border: 1px solid #eee;
  border-radius: 8px;
  margin-bottom: 20px;
}
</style>